name: deploy to aks prod-env
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  build: 
    uses: ./.github/workflows/CI-java-build-package-maven.yml
    secrets: inherit
  deploy-Prod:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: shafi14 # name of Docker Hub ID
      IMAGE_NAME: javaappaksdeploy
      IMAGE_TAG: ${{ github.run_number }}
      
      CLUSTER_NAME: shafi-aks-test2
      RESOURSE_GROUP: shafi-rg2
    needs: [build]
    environment: Prod
    steps:
      - name: Display the path
        run: pwd
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: mywebapp-artifact
          path: ${{github.workspace}}
         

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
          
    

        # Set the target AKS cluster..
      - name: Deploy to AKS
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURSE_GROUP }}
      
      - name: Apply Kubernetes deployment
        uses: Azure/k8s-deploy@v1
        with:
          namespace: prod
          manifests: |
            kubernetes/deployment.yml
          images: |
            shafi14/javaappaksdeploy:${{ github.run_number }}
